# Generated by Django 3.2.4 on 2021-07-09 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fitwellNG_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer Not To Say')], max_length=50, verbose_name='Sex')),
                ('nationality', models.CharField(choices=[('NIG', 'Nigerian')], max_length=50, verbose_name='Country of Origin')),
                ('state', models.CharField(choices=[('KW', 'Kwara')], max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Enter your weight in kg', max_digits=5, verbose_name='Weight')),
                ('height', models.DecimalField(decimal_places=2, help_text='Enter your height in cm', max_digits=5, verbose_name='Height')),
                ('security', models.TextField(verbose_name='Security question')),
                ('security_answer', models.CharField(max_length=50, verbose_name='Answer')),
                ('image', models.ImageField(default='image\\default.png', null=True, upload_to=fitwellNG_app.models.get_image_path, verbose_name='Image')),
                ('phone_no', models.CharField(max_length=14, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('day', models.CharField(choices=[('mon', 'monday'), ('tue', 'tuesday'), ('wed', 'wednesday'), ('thur', 'thursday'), ('fri', 'friday'), ('sat', 'saturday'), ('sun', 'sunday')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_name', models.CharField(help_text='squats, Jumping-Jack, etc', max_length=200)),
                ('description', models.TextField(help_text='How is it being done?')),
                ('repetition_no', models.IntegerField(help_text='Expected number of repetition daily')),
                ('repetition_achieved_today', models.IntegerField(blank=True, default=0, null=True)),
                ('repetition_achieved_total', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(help_text='Beginners, Intermediate, Expert...', max_length=200)),
                ('duration', models.IntegerField(help_text='weeks')),
                ('daily_duration', models.IntegerField(help_text='Time in Mins to spend daily')),
                ('time_spent_today', models.IntegerField(blank=True, default=0, help_text='In Minutes', null=True)),
                ('time_spent_total', models.IntegerField(blank=True, default=0, help_text='In Minutes', null=True)),
                ('routines', models.ManyToManyField(to='fitwellNG_app.Routine')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlansList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField(help_text='weeks')),
                ('start_date', models.DateField(null=True)),
                ('plan', models.ManyToManyField(to='fitwellNG_app.PlanTable')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fitwellNG_app.user')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitwellNG_app.workoutplanlist')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlans',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fitwellNG_app.user')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitwellNG_app.mealplanslist')),
            ],
        ),
    ]
