# Generated by Django 3.2.4 on 2021-07-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitwellNG_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallists',
            name='breakfast_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meallists',
            name='breakfast_meal_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='meallists',
            name='dinner_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meallists',
            name='dinner_meal_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='meallists',
            name='lunch_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meallists',
            name='lunch_meal_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meallists',
            name='category',
            field=models.CharField(help_text='category of this plan may be similar to name e.g weight loss. Must be repeated for each day in the plan', max_length=300),
        ),
        migrations.AlterField(
            model_name='meallists',
            name='day',
            field=models.IntegerField(help_text='specify day no. e.g day 1 out of 30 days plan'),
        ),
        migrations.AlterField(
            model_name='meallists',
            name='name',
            field=models.CharField(help_text='Meal plan name e.g. weight shred. Must be repeated for each day in the plan', max_length=300),
        ),
    ]
