# Generated by Django 3.2.4 on 2021-06-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitwellNG_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(choices=[('NIG', 'Nigerian')], max_length=50, verbose_name='Country of Origin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer Not To Say')], max_length=50, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('KW', 'Kwara')], max_length=50),
        ),
    ]
