# Generated by Django 3.2.4 on 2021-06-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitwellNG_app', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
