# Generated by Django 3.2.4 on 2021-07-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitwellNG_app', '0002_auto_20210713_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallists',
            name='calories_intake',
        ),
    ]
