# Generated by Django 3.2.4 on 2021-07-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitwellNG_app', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
