# Generated by Django 3.2.4 on 2021-06-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitwellNG_app', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=222),
            preserve_default=False,
        ),
    ]
