# Generated by Django 3.2.4 on 2021-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitwellNG_app', '0004_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
